name: Build GUPF AWS Lambda Package

on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build-and-package:
    runs-on: ubuntu-latest
    steps:
      # 1. Mengunduh kode Anda dari repositori ke server
      - name: Checkout repository
        uses: actions/checkout@v4

      # 2. Membangun image Docker (persis seperti yang kita lakukan secara lokal)
      - name: Build the Docker image
        run: docker build . -t gupf-image

      # ... bagian lain dari workflow ...
      - name: Extract Lambda package
        run: |
          mkdir build
          CONTAINER_ID=$(docker create gupf-image)
          # Perintah ini menyalin seluruh isi folder /var/task ke folder build
          docker cp $CONTAINER_ID:/var/task ./build
          docker rm $CONTAINER_ID
          
          # --- PERBAIKAN DI SINI ---
          # Masuk ke dalam folder 'task' yang baru dibuat, lalu buat zip dari semua isinya.
          # Tanda '.' berarti "semua file dan folder di direktori saat ini".
          cd build/task && zip -r ../../gupf-deployment-package.zip .
          # ------------------------
