# Nama workflow yang akan muncul di tab Actions GitHub
name: Build and Deploy GUPF to Lambda (v-Final)

# Pemicu: Workflow ini akan berjalan setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches:
      - main
  workflow_dispatch: # Memungkinkan Anda menjalankan workflow ini secara manual

jobs:
  build:
    # Menggunakan runner standar dari GitHub
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Mengunduh kode dari repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Membuat direktori 'package' untuk menampung semua file
      - name: Create package directory
        run: mkdir package

      # Langkah 3: Menginstal SEMUA library LANGSUNG ke dalam folder 'package'
      - name: Install dependencies into package folder
        run: |
          docker run --entrypoint /bin/sh --rm -v "$(pwd)":/var/task public.ecr.aws/lambda/python:3.12 -c "pip install -r /var/task/requirements.txt -t /var/task/package/ && exit 0"
      
      # Langkah 4: Menyalin file kode utama ke dalam folder 'package'
      - name: Add function code to package
        run: cp gupf_brain_aws.py package/

      # Langkah 5: Membuat paket ZIP dari isi folder 'package'
      - name: Create deployment package
        run: |
          cd package
          zip -r ../gupf-deployment-package.zip .
          
      # Langkah 6: Mengunggah file ZIP sebagai artifact
      - name: Upload deployment package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gupf-deployment-package
          path: gupf-deployment-package.zip
