# Nama workflow yang akan muncul di tab Actions GitHub
name: Build and Deploy GUPF to Lambda

# Pemicu: Workflow ini akan berjalan setiap kali ada 'push' ke branch 'main'
on:
  push:
    branches:
      - main
  workflow_dispatch: # Memungkinkan Anda menjalankan workflow ini secara manual

jobs:
  build:
    # Menggunakan runner standar dari GitHub
    runs-on: ubuntu-latest

    steps:
      # Langkah 1: Mengunduh kode dari repositori Anda
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Mengatur versi Python yang akan digunakan oleh runner
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # Langkah 3: Menginstal SEMUA library ke dalam folder 'python' menggunakan Docker
      - name: Install dependencies using Lambda Docker image
        # INI ADALAH PERBAIKANNYA: Menambahkan --entrypoint /bin/sh
        # Ini memaksa container untuk menjalankan shell command, bukan entrypoint defaultnya.
        run: |
          docker run --entrypoint /bin/sh --rm -v "$(pwd)":/var/task public.ecr.aws/lambda/python:3.12 -c "pip install -r /var/task/requirements.txt -t /var/task/python/lib/python3.12/site-packages/ && exit 0"
      
      # Langkah 4: Membuat paket ZIP yang siap di-deploy
      - name: Create deployment package
        run: |
          mkdir deployment
          cp gupf_brain_aws.py deployment/
          cp -r python/ deployment/
          cd deployment
          zip -r ../gupf-deployment-package.zip .
          
      # Langkah 5: Mengunggah file ZIP sebagai artifact
      - name: Upload deployment package as artifact
        uses: actions/upload-artifact@v4
        with:
          name: gupf-deployment-package
          path: gupf-deployment-package.zip
