# Nama workflow yang akan muncul di daftar Actions
name: Build GUPF AWS Lambda Package

# Kapan workflow ini akan dijalankan
on:
  # 1. Setiap kali ada 'push' ke branch 'main'
  push:
    branches: [ "main" ]
  # 2. Agar bisa dijalankan secara manual dari tab Actions
  workflow_dispatch:

# Daftar pekerjaan yang harus dilakukan
jobs:
  # Kita hanya punya satu pekerjaan, yaitu 'build-and-package'
  build-and-package:
    # Menggunakan server Linux (Ubuntu) terbaru yang disediakan GitHub
    runs-on: ubuntu-latest
    
    # Langkah-langkah yang akan dijalankan di server tersebut
    steps:
      # Langkah 1: 'Checkout' kode dari repositori Anda ke server
      - name: Checkout repository
        uses: actions/checkout@v4

      # Langkah 2: Membangun image Docker menggunakan Dockerfile Anda
      - name: Build the Docker image
        run: docker build -t gupf-image .

      # Langkah 3: Ekstrak folder 'package' dari image dan buat file .zip
      - name: Create Lambda deployment package
        run: |
          mkdir build
          CONTAINER_ID=$(docker create gupf-image)
          docker cp $CONTAINER_ID:/var/task/package ./build/
          docker rm $CONTAINER_ID
          cd build/package && zip -r ../../gupf-deployment-package.zip .
          
      # Langkah 4: Unggah file .zip yang sudah jadi sebagai 'artifact'
      - name: Upload Lambda package as an artifact
        uses: actions/upload-artifact@v4
        with:
          # Nama artifact yang bisa diunduh
          name: gupf-lambda-package
          # Lokasi file yang akan diunggah
          path: gupf-deployment-package.zip
